### ISSUE TITLE
Add RSS feed to blog

### ISSUE THREAD

**Issue by melomac** [nmggithub/wts#1]
Hi

Would you please be so kind to consider adding a RSS feed for [wts.dev/posts/](https://wts.dev/posts/)?

I'd love to add your posts to my daily reading routine.

Cheers!

EDIT:
I came by https://wts.dev/feed.xml at the bottom of https://wts.dev/posts/tcc-sql-injection/
but Feedbin doesn't seem to like it 😬

**Comment by nmggithub** [comment]
Hello @melomac!

The feed linked there is an Atom feed. I have, indeed, found that some RSS readers struggle to support it. I'll take a look at yours and see what I can do. I'm hesitant to switch to RSS, especially after already establishing the Atom feed, but it's something I will consider.

**Comment by nmggithub** [comment]
Commit 26fe0f8435f8b2690b609eb82a7e18ff4ec25104 appears to have fixed another feed reader that had issues previously, but Feedbin still seems unhappy. Thankfully, though, they appear to be open source, so I'm looking through their code right now to see what is tripping it up.

**Comment by nmggithub** [comment]
52891cb4fe18551909b5269eb85b2f95ac54bc19 seems to fix the issues with Feedbin on my end. I'm going to close this issue now, but feel free to reopen it if you are still having issues!

**Comment by melomac** [comment]
Indeed, this is awesome, thanks!

**Comment by nmggithub** [comment]
> Indeed, this is awesome, thanks!

Of course!
